name: fahri_genz_vibe
description: A simple Flutter client for FahriGenzVibe (iTunes preview player)
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  audioplayers: ^5.0.1
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^12.0.4
  audio_service: ^0.18.16
  just_audio: ^0.9.33
  audio_session: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
